### ISSUE TITLE
[False Alarm] Mod is not working.

### ISSUE THREAD

**Issue by danylopez123** [KBMackenzie/CultMusicLoader#1]
I've tried to install this mod, i do have a music installed in the plugins folder, the console says it loaded without the text saying there's no musics.

However, the Music selector doesn't show up, not even pressing G, is this related because of the game updates and the mod doesn't work?
I've started this from a new game file + i did make sure i had the required files as well no other mod was loaded to avoid conflicts.

**Comment by kbmackenzie** [comment]
Does the BepInEx console show any errors at all? The music selector menu should be in the pause menu. Is it not there at all? Also, by "the console says it loaded" I'm assuming you mean you got the _"Loaded Cult Music Loader!"_ message in your console, right?

Do any errors show up in the BepInEx console? When an update breaks a mod there are usually many errors in the console. If any errors have shown up at all, let me know.
 
I've been away from COTL modding (and modding in general) for a while and I haven't tested this mod with the latest version of the game yet, but it should work fine. I actually helped another person install it the other day and it worked fine for them.

Also: Be sure your music files have names ending in "_cult". A lot of people seem to miss this, sadly. The supported extensions are .mp3, .wav and .ogg, and your file's name _must_ end in in "_cult".
An example of a valid name is `example_cult.mp3`. If your file is named something like `example.mp3` instead, the mod will ignore it. (This is done for better compatibility with other mods that may use audio files.)

Let me know if any of this helps!

**Comment by danylopez123** [comment]
Oh, i see.
That is what i've been doing, sorry that i haven't explained that.

From what i've been saying about the console, it loaded fine without the text saying that no musics were found:

[Info   :   BepInEx] Loading [Cult Music Loader 1.0.0]
[Info   :Cult Music Loader] Loaded Cult Music Loader!
[Message:   BepInEx] Chainloader startup complete

I did the thing of renaming a file ending it with _cult.mp3

Also.. i think i have found the problem: This doesn't play anything during the Intro when you start a new file.

Previously trying to get this working, i was doing this in a fresh new game and no music menu was showing up, then.. i've tried to load a file i had with some progress in it and it played the music i've added as an example.

From a fresh new file, the music started to happen when i got to the cult bas.... OH GOD, I'VE FRIGGIN' MISSED THAT DETAIL THAT ONLY PLAYS AT THE CULT BASE

Okay.. this was just a false alarm, i've missed that part somehow, my bad with this report, sorry about that, closing.
